root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/app/main.go"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  # Delay (in milliseconds) before rebuilding after a file change (helps with frequent changes)
  delay = 1000
  # Delay (in milliseconds) to wait for the old process to be killed before starting a new one
  kill_delay = 500
  # File extensions to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]
  # Directories to ignore changes from (like build output, vendor libraries, etc.)
  exclude_dir = ["tmp", "vendor", "assets", "testdata"]
  # Regex patterns to exclude from triggering a rebuild (for example, test files)
  exclude_regex = ["_test.go"]
  # Stop the build process if errors occur (helpful during development)
  stop_on_error = true
  # Log file for build errors (saved in the tmp_dir)
  log = "build-errors.log"

[color]
  # Customize output colors (optional)
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  # Disable timestamps in logs for cleaner output
  time = false

[misc]
  # Ensures the temporary directory is cleaned when Air exits (important to free ports)
  clean_on_exit = true
